%left      '||'
%left      '&&'
%left      '==' '!='
%left      '+' '-'
%left      '*' '/' '%'
%nonassoc  '<=' '>=' '<' '>'
%right     '!'
%left      ':'
%nonassoc  '!'
%nonassoc  '|'
%nonassoc  '(' ')' '[' ']' '{' '}'
%nonassoc  '.'
%nonassoc  '->'


%%

prog  : stmts                               
      | header stmts                        
      ;
stmts :                            
      | line 'N' stmts                      
      | block stmts                         
      ;

header : module ident 'N' imports           ;
imports :                        
        | import 'N' imports                
        | import_c 'N' imports              
        ;



symbol : ident                              
       | ident '::' ident                   
       ;

mfnrec :                           
       | '{' paramsA '}'                    
       ;


initialiser : '{' exprsA '}'                
            | string_c                      
            ;
minitialiser : initialiser                  
             |                     
             ;

line : let pattern '=' expr                         
     | index '=' expr                               
     | index                                        
     | type symbol anno_t                           
     | return mexpr                                 
     | data symbol type_ minitialiser               
     ;
block : if_                                         
      | fn mfnrec ident '(' paramsA ')' mtype scope 
      | while condition scope                       
      | for expr scope                              
      | for expr '->' pattern scope                 
      | switch_                                     
      ;

scope  : 'I' stmts 'D'                      
       | ';' line 'N'                       
       | ';' 'N'                            
       ;

condition : expr                            
          | expr '->' pattern               
          ;


param   : ident type_                       ;
params  :                        
        | params1                           
        ;
params1 : param                             
        | param ',' params1                 
        ;
paramsN : param 'N'                         
        | param 'N' paramsN                 
        ;
paramsA : params                            
        | 'I' paramsN 'D'                   
        ;


if_   : if condition scope else_            
      | if condition 'N' else_              
      ;
else_ : else scope                          
      | else if_                            
      |                            
      ;


switch_ : switch expr 'I' cases1 'D'        
       | switch expr                        
       ;
cases1 : case                               
      | case cases1                         
      ;
case : pattern scope                        ;


patterns  :                      
          | patterns1                       
          ;
patterns1 : pattern                         
          | pattern ',' patterns1           
          ;
patternsSem : patterns                      
           | patterns ';' patternsSem       
           ;

pattern  : '_'                              
         | literal                          
         | '-' int_c                        
         | ident                            
         | null                             
         | '(' patterns ')'                 
         | '[' patternsSem ']'              
         | pattern '|' expr                 
         | pattern '|' expr '->' pattern    
         | symbol '(' patterns ')'          
         | ordinal_t '(' pattern ')'        
         | pattern ':' type_                
         ;


exprs  :                         
       | exprs1                             
       ;
exprs1 : expr                               
       | expr ',' exprs1                    
       ;
exprsN : expr 'N'                           
       | expr 'N' exprsN                    
       ;
mexpr  :                           
       | expr                               
       ;
exprsA : exprs                              
       | 'I' exprsN 'D'                     
       ;

call : symbol '(' exprsA ')'                   
     | '{' exprsA '}' '.' ident '(' exprsA ')' 
     ;

index  : symbol                             
       | index '[' expr ']'                 
       | index '.' ident                    
       | index '.' symbol '(' exprsA ')'    
       | call                               
       ;

expr   : literal                            
       | infix                              
       | prefix                             
       | call                               
       | symbol                             
       | '(' exprsA ')'                     
       | ordinal_t '(' exprsA ')'           
       | null                               
       | expr '.' ident                     
       | expr '[' expr ']'                  
       | expr ':' type_                     
       | expr '.' ident '(' exprsA ')'      
       | expr '[' mexpr '..' mexpr ']'      
       | '[' mexpr '..' mexpr ']'           
       | '[' exprsA ']'                     
       ;

literal : int_c                             
        | float_c                           
        | char_c                            
        | string_c                          
        | true                              
        | false                             
        ;

infix : expr '+' expr                       
      | expr '-' expr                       
      | expr '*' expr                       
      | expr '/' expr                       
      | expr '%' expr                       
      | expr '<' expr                       
      | expr '>' expr                       
      | expr '<=' expr                      
      | expr '>=' expr                      
      | expr '==' expr                      
      | expr '&&' expr                      
      | expr '||' expr                      
      | expr '!=' expr                      
      ;

prefix : '-' expr                           
       | '+' expr                           
       | '!' expr                           
       ;

mtype  :                           
       | type_                              
       ;
types  :                           
       | types1                             
       ;
types1 : type_                              
       | type_ ',' types1                   
       ;
types1_ : type_                             
        | type_ ';' types1_                 
        ;
    
type_         : symbol                      
              | ordinal_t                   
              | aggregate_t                 
              ;

ordinal_t   : bool                          
            | i16                           
            | i32                           
            | i64                           
            | f32                           
            | f64                           
            | char                          
            | '@' type_                     
            ;

aggregate_t : table_t                       
              | array_t                     
              | tup_t                       
              | adt_t                       
              | sparse_t                    
              | map_t                       
              | range_t                     
              | fn '(' types ')' type_      
              ;


adt_t    : '{' adtFields '}'                ;
array_t  : '[' int_c type_ ']'              ;
table_t  : '[' types1_ ']'                  
         | string                           
         ;
tup_t    : '(' types ')';                   
sparse_t : sparse '[' types1_ ']';          
map_t    : map '[' type_ ']' type_ ;
range_t  : '[' '..' ']' type_ ;


anno_t   : ordinal_t                        
         | symbol                           
         | '(' types1 ')'                   
         | '(' paramsA ')'                  
         | array_t                          
         | table_t                          
         | sparse_t                         
         | '{' ADTFieldsA '}'               
         ;


adtFields :                        
          | adtFields1                      
          ;
adtFields1 : adtField                       
           | adtField '|' adtFields1        
           ;
adtField : type_                            
         | null                             
         ;


ADTFieldsA : ADTFields1                     
           | 'I' ADTFieldsN 'D'             
           ;
ADTFieldsN : ADTField 'N'                   
           | ADTField 'N' ADTFieldsN        
           ;
ADTFields1 : ADTField                       
           | ADTField '|' ADTFields1        
           ;
ADTField : ident '(' types ')'              
         | type_                            
         | null                             
         ;
